Delete logging.py
AttributeError: module 'logging' has no attribute 'basicConfig' (consider renaming 'f:\python\Expense-tracker\logging.py' since it has the same name as the standard library module named 'logging' and prevents importing that standard library module)